ARG CROSS_BASE_IMAGE
FROM ${CROSS_BASE_IMAGE}
# Note that we're assuming an Ubuntu-based image in all cases though

ARG OPENSSL_BUILD_VER=3.0.12
RUN cd /usr/local/src/ && curl -sLO https://www.openssl.org/source/openssl-${OPENSSL_BUILD_VER}.tar.gz && \
    tar xzvf openssl-${OPENSSL_BUILD_VER}.tar.gz && cd openssl-${OPENSSL_BUILD_VER} && \
    CROSS_COMPILE="x86_64-linux-musl-" ./Configure --prefix=/usr/local/x86_64-linux-musl linux-x86_64 && make && make install
